export const SITE = {
  name: "FaishonFit",
  tagline: "Fit for the world you're building",
  description:
    "FaishonFit is a fashion house for people in motion — considered tailoring, technical fabrics, and silhouettes cut for the studio, the street, and everything after.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://faishonfit.com",
};

export const MAIN_NAV = [
  { label: "Women", href: "/category/women" },
  { label: "Men", href: "/category/men" },
  { label: "Streetwear", href: "/category/streetwear" },
  { label: "Sportswear", href: "/category/sportswear" },
  { label: "Maison", href: "/category/luxury" },
  { label: "Lookbook", href: "/lookbook" },
] as const;

export const FOOTER_LINKS = {
  Shop: [
    { label: "New Arrivals", href: "/shop?filter=new" },
    { label: "Best Sellers", href: "/shop?filter=bestsellers" },
    { label: "Women", href: "/category/women" },
    { label: "Men", href: "/category/men" },
    { label: "Gift Cards", href: "/gift-cards" },
  ],
  Company: [
    { label: "About FaishonFit", href: "/about" },
    { label: "Sustainability", href: "/sustainability" },
    { label: "Careers", href: "/careers" },
    { label: "Press", href: "/press" },
    { label: "Contact", href: "/contact" },
  ],
  Support: [
    { label: "FAQ", href: "/faq" },
    { label: "Shipping", href: "/faq#shipping" },
    { label: "Returns & Exchanges", href: "/returns-policy" },
    { label: "Size Guide", href: "/size-guide" },
    { label: "Track Order", href: "/account/orders" },
  ],
  Legal: [
    { label: "Privacy Policy", href: "/privacy-policy" },
    { label: "Terms & Conditions", href: "/terms-conditions" },
    { label: "Accessibility", href: "/accessibility" },
  ],
} as const;

export const SOCIAL_LINKS = [
  { label: "Instagram", href: "https://instagram.com/faishonfit" },
  { label: "TikTok", href: "https://tiktok.com/@faishonfit" },
  { label: "Pinterest", href: "https://pinterest.com/faishonfit" },
  { label: "X", href: "https://x.com/faishonfit" },
] as const;

export const COLLECTIONS = [
  {
    id: "women",
    name: "Women",
    slug: "women",
    tagline: "Structured softness",
    itemCount: 214,
    tone: "from-[#2c2420] via-[#171310] to-[#0a0a0b]",
  },
  {
    id: "men",
    name: "Men",
    slug: "men",
    tagline: "Precision tailoring",
    itemCount: 186,
    tone: "from-[#1c2420] via-[#12140f] to-[#0a0a0b]",
  },
  {
    id: "streetwear",
    name: "Streetwear",
    slug: "streetwear",
    tagline: "Off-duty armor",
    itemCount: 142,
    tone: "from-[#241a2c] via-[#150f18] to-[#0a0a0b]",
  },
  {
    id: "sportswear",
    name: "Sportswear",
    slug: "sportswear",
    tagline: "Built for output",
    itemCount: 97,
    tone: "from-[#1a2430] via-[#0f151c] to-[#0a0a0b]",
  },
  {
    id: "luxury",
    name: "Maison",
    slug: "luxury",
    tagline: "The archive line",
    itemCount: 48,
    tone: "from-[#2c2011] via-[#181206] to-[#0a0a0b]",
  },
  {
    id: "seasonal",
    name: "FW26 Drop",
    slug: "seasonal",
    tagline: "This season only",
    itemCount: 63,
    tone: "from-[#241414] via-[#150c0c] to-[#0a0a0b]",
  },
] as const;

export const TRENDING_PRODUCTS = [
  {
    id: "p1",
    slug: "wool-crepe-tailored-blazer",
    name: "Wool-Crêpe Tailored Blazer",
    category: "Women / Outerwear",
    price: 428,
    compareAtPrice: 540,
    rating: 4.8,
    reviewCount: 216,
    colors: ["#0A0A0B", "#8B4225", "#3E3A34"],
    tone: "from-[#2a2622] to-[#0d0c0b]",
    badge: "20% OFF",
  },
  {
    id: "p2",
    slug: "technical-shell-overcoat",
    name: "Technical Shell Overcoat",
    category: "Men / Outerwear",
    price: 512,
    compareAtPrice: null,
    rating: 4.9,
    reviewCount: 158,
    colors: ["#0A0A0B", "#4A4E52"],
    tone: "from-[#1b1f22] to-[#0a0b0c]",
    badge: "NEW",
  },
  {
    id: "p3",
    slug: "cropped-boxing-hoodie",
    name: "Cropped Boxing Hoodie",
    category: "Streetwear / Tops",
    price: 148,
    compareAtPrice: 185,
    rating: 4.6,
    reviewCount: 342,
    colors: ["#8B4225", "#0A0A0B", "#C6A664"],
    tone: "from-[#241a17] to-[#0d0a09]",
    badge: "20% OFF",
  },
  {
    id: "p4",
    slug: "compression-run-tight",
    name: "Compression Run Tight",
    category: "Sportswear / Bottoms",
    price: 96,
    compareAtPrice: null,
    rating: 4.7,
    reviewCount: 501,
    colors: ["#0A0A0B", "#1E2A3A"],
    tone: "from-[#171b22] to-[#0a0b0d]",
    badge: null,
  },
  {
    id: "p5",
    slug: "silk-slip-column-dress",
    name: "Silk Slip Column Dress",
    category: "Maison / Eveningwear",
    price: 690,
    compareAtPrice: null,
    rating: 5.0,
    reviewCount: 64,
    colors: ["#C6A664", "#0A0A0B"],
    tone: "from-[#2c2415] to-[#0d0b08]",
    badge: "ARCHIVE",
  },
  {
    id: "p6",
    slug: "raw-selvedge-denim-jacket",
    name: "Raw Selvedge Denim Jacket",
    category: "Men / Outerwear",
    price: 265,
    compareAtPrice: 310,
    rating: 4.5,
    reviewCount: 289,
    colors: ["#26364A", "#0A0A0B"],
    tone: "from-[#1a222e] to-[#0a0c0f]",
    badge: "20% OFF",
  },
  {
    id: "p7",
    slug: "featherweight-down-vest",
    name: "Featherweight Down Vest",
    category: "Sportswear / Outerwear",
    price: 178,
    compareAtPrice: null,
    rating: 4.6,
    reviewCount: 133,
    colors: ["#8B4225", "#0A0A0B", "#F7F5F1"],
    tone: "from-[#241813] to-[#0d0a08]",
    badge: null,
  },
  {
    id: "p8",
    slug: "pleated-wide-leg-trouser",
    name: "Pleated Wide-Leg Trouser",
    category: "Women / Bottoms",
    price: 214,
    compareAtPrice: null,
    rating: 4.7,
    reviewCount: 177,
    colors: ["#0A0A0B", "#3E3A34", "#C6A664"],
    tone: "from-[#221f1a] to-[#0c0b09]",
    badge: "NEW",
  },
] as const;

export const NEW_ARRIVALS = [
  {
    id: "n1",
    slug: "asymmetric-drape-coat",
    name: "Asymmetric Drape Coat",
    category: "Women",
    price: 486,
    tone: "from-[#231f1c] to-[#0b0a09]",
  },
  {
    id: "n2",
    slug: "merino-half-zip",
    name: "Merino Half-Zip",
    category: "Men",
    price: 165,
    tone: "from-[#1c211f] to-[#0a0b0a]",
  },
  {
    id: "n3",
    slug: "cargo-utility-pant",
    name: "Cargo Utility Pant",
    category: "Streetwear",
    price: 138,
    tone: "from-[#211c19] to-[#0a0908]",
  },
  {
    id: "n4",
    slug: "featherlight-windbreaker",
    name: "Featherlight Windbreaker",
    category: "Sportswear",
    price: 122,
    tone: "from-[#19212a] to-[#090b0e]",
  },
  {
    id: "n5",
    slug: "hand-finished-cashmere-scarf",
    name: "Hand-Finished Cashmere Scarf",
    category: "Maison",
    price: 210,
    tone: "from-[#251d10] to-[#0b0906]",
  },
  {
    id: "n6",
    slug: "canvas-tote-carryall",
    name: "Canvas Tote Carryall",
    category: "Accessories",
    price: 88,
    tone: "from-[#1f1c19] to-[#0a0908]",
  },
  {
    id: "n7",
    slug: "ribbed-turtleneck",
    name: "Ribbed Turtleneck",
    category: "Women",
    price: 94,
    tone: "from-[#201c22] to-[#0a090c]",
  },
  {
    id: "n8",
    slug: "leather-chelsea-boot",
    name: "Leather Chelsea Boot",
    category: "Men",
    price: 298,
    tone: "from-[#1e1815] to-[#0a0807]",
  },
] as const;

export const TESTIMONIALS = [
  {
    id: "t1",
    name: "Amara Osei",
    location: "Brooklyn, NY",
    rating: 5,
    verified: true,
    body: "The wool-crêpe blazer fits like it was pattern-cut for me specifically. First online order in years where I didn't need a single alteration.",
    purchased: "Wool-Crêpe Tailored Blazer",
  },
  {
    id: "t2",
    name: "Diego Fuentes",
    location: "Austin, TX",
    rating: 5,
    verified: true,
    body: "Shell overcoat has survived three genuinely miserable commutes so far. Seams are taped, zipper is smooth, and it still looks sharp in a meeting.",
    purchased: "Technical Shell Overcoat",
  },
  {
    id: "t3",
    name: "Priya Nair",
    location: "Toronto, ON",
    rating: 4,
    verified: true,
    body: "Sizing runs slightly generous, so I'd size down — but once I exchanged, the compression tight has genuinely replaced three other brands in rotation.",
    purchased: "Compression Run Tight",
  },
  {
    id: "t4",
    name: "Jonah Whitfield",
    location: "London, UK",
    rating: 5,
    verified: true,
    body: "Ordered the silk slip dress for a gallery opening. Fabric weight and drape read as expensive in person — more than the price tag would suggest.",
    purchased: "Silk Slip Column Dress",
  },
] as const;

export const LOOKBOOK_EDITORIALS = [
  {
    id: "e1",
    issue: "FW26 — No. 01",
    title: "The Long Grey Season",
    tone: "from-[#26221d] to-[#0b0a08]",
  },
  {
    id: "e2",
    issue: "FW26 — No. 02",
    title: "After Hours, Downtown",
    tone: "from-[#1d2622] to-[#080b0a]",
  },
  {
    id: "e3",
    issue: "FW26 — No. 03",
    title: "Studio to Street",
    tone: "from-[#221d26] to-[#0a080b]",
  },
  {
    id: "e4",
    issue: "FW26 — No. 04",
    title: "Field Notes: Reykjavík",
    tone: "from-[#1d2226] to-[#08090b]",
  },
] as const;
